### PR TITLE
Update serialport to 6.0.4

### PR DESCRIPTION
**Pull request by Apollon77**
Much more stable in my other adapters and projects ...

### CODE REVIEW

**Comment by Apollon77** [comment]
PS: If you want to add real (also "serial" testing) you should have a look at "virtual-serialport"

**Comment by hobbyquaker** [comment]
PRs for more extensive testing are highly appreciated ;-)

**Comment by Apollon77** [comment]
;-)) will see what I can do ... maybe I find some time beside testing basics for all ioBroker "own" Adapters :-)

**Comment by Apollon77** [comment]
oooh ... just saw ... Readline was used too ... then you need to change a bit more!!
The Parsers are now "Stream" stuff ...

I will prepare a PR - sorry don't saw that

**Pull request merged**
